[env:ttgo-t-beam-1W]
board = esp32-s3-devkitm-1
board_build.mcu = esp32s3
board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.psram_type = opi
build_flags =
	${common.build_flags}
	${common.usb_flags}
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX127X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D TTGO_T_BEAM_1W
	-D BOARD_HAS_PSRAM
lib_deps =
	${common.lib_deps}
	${common.display_libs}
	adafruit/Adafruit SH110X @ 2.1.15
