[env:lilygo-t-internet-poe-oe5bpa-lora-hat]
board = esp32doit-devkit-v1
build_flags =
	${common.build_flags}
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX126X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D LILYGO_T_INTERNET_POE_OE5BPA_LORA_HAT
lib_deps =
	${common.lib_deps}
	${common.display_libs}
