[env:RAK3112]
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags =
	${common.build_flags}
	${common.usb_flags}
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_SX127X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D BOARD_HAS_PSRAM
	-D RAK3112
lib_deps =
	${common.lib_deps}
