[env:ttgo_lora32_teth_elite]
board = esp32s3box
board_build.mcu = esp32s3
board_upload.flash_size = 16MB
build_flags =
    ${common.build_flags}
	${common.usb_flags}
    -D TTGO_LORA32_TETH_ELITE
    -D BOARD_HAS_PSRAM
lib_deps =
	${common.lib_deps}