name: Commit Test Build

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                target:
                    - "ttgo-lora32-v21"
                    - "heltec-lora32-v2"
                    - "heltec_wifi_lora_32_V3"
                    - "heltec_wireless_stick"
                    - "heltec_wireless_stick_lite_v3"
                    - "heltec_ht-ct62"
                    - "ESP32_DIY_LoRa"
                    - "ESP32_DIY_1W_LoRa"
                    - "ttgo-t-beam-v1_2"
                    - "ttgo-t-beam-v1"
                    - "ttgo-t-beam-v1_SX1268"
                    - "ttgo-t-beam-v1_2_SX1262"
                    - "ESP32_DIY_LoRa_A7670"
                    - "heltec_wireless_tracker"
                    - "OE5HWN_MeshCom"
                    - "WEMOS-LOLIN32-OLED-DIY"
                    - "ttgo-lora32-v21-915"
                board_type:
                    - "esp32"
                    - "esp32s3"
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install PlatformIO Core
              run: pip install --upgrade platformio

            - name: Determine board type
              id: determine-board
              run: |
                if [[ "${{ matrix.board_type }}" == "esp32s3" ]]; then
                  echo "BOARD_ENV=esp32s3" >> $GITHUB_ENV
                else
                  echo "BOARD_ENV=esp32" >> $GITHUB_ENV
                fi
              shell: bash

            - name: Build target
              run: pio run -e ${{ matrix.target }}

            - name: Build FS
              run: pio run --target buildfs -e ${{ matrix.target }}